export default {
  data() {
    return {
      defaultMessageProperties: {
        "upload_form.no_file_to_upload": "No file selected to upload",
        "upload_form.no_files_to_upload": "No files selected to upload",
        "upload_form.labeltext.select_file": "Select file to upload",
        "upload_form.labeltext.select_files": "Select files to upload",
        "upload_form.labeltext.remove_file_from_list": "Remove file '{0}' from list",
        "upload_form.labeltext.remove_all_files_from_list": "Remove all files from list",
        "upload_form.labeltext.file_uploading": "file to upload",
        "upload_form.labeltext.files_uploading": "files to upload",
        "upload_form.labeltext.comment": "Comment:",
        "upload_form.buttontext.upload_file": "Upload file",
        "upload_form.buttontext.upload_files": "Upload files",
        "upload_form.buttontext.cancel": "Cancel",
        "upload_form.placeholder.comment": "Please type in a specific comment",
        "upload_form.system_message.found_duplicate_file": "Found duplicate file (not added again)",
        "upload_form.system_message.upload_success": "Upload successful",
        "upload_form.system_message.upload_failed": "Upload failed",
        "upload_form.system_message.fill_required": "Fill all required fields",
        "upload_form.system_message.the_following_errors_occurred": "The following errors occurred!",
        "upload_form.system_message.an_unknown_error_occurred": "An unknown error occurred!",
        "upload_form.system_message.only_one_file_allowed": "Only one file allowed!",
        "upload_form.system_message_total_size_of_files_too_large": "Total size of files too large!",
        "upload_form.system_message.duplicate_file": 'Duplicate file "{0}" found (not added to list again)',
        "upload_form.system_message.not_allowed_file_type": 'File "{0}" has not allowed file type ({1})',
        "upload_form.system_message.all_files_are_uploaded_successfully": "All files are uploaded successfully",
        "upload_form.system_message.some_files_are_not_uploaded_successfully": "Some files are not uploaded successfully",
        "upload_form.system_message.file_size_too_large": 'File size of "{0}" too large ({1})',
        "upload_form.headline.summary_of_all_files": "Summary of all files",
        "upload_form.headline.list_of_selected_files": "List of selected files",
        "upload_form.headline.select_additional_files": "Select additional files",
        "upload_form.headline.select_new_file": "Chosen the wrong file? Select a new one",
        "upload_form.allowed_file_types": "Allowed file types:",
        "upload_form.max_total_upload_size": "Max. total upload size:",
        "upload_form.max_file_upload_size": "Max. file upload size:",
        "upload_form.or": "or",
        "upload_form.drag_and_drop": "drag (and drop)",
        "upload_form.additional": "additional",
        "upload_form.new": "new",
        "upload_form.files_to_this_area": "files to this area",
        "upload_form.tooltip.toggle_list_of_allowed_file_types": "Toggle list of allowed file types",
        "upload_form.reset_upload": "Reset upload",
        "upload_form.tooltip.all_files_will_be_removed": "All files will be remove from upload-list!",
        "upload_form.select_image": "Select image",
        "upload_form.select_file": "Select file",
        "upload_form.drag_and_drop_file_here": "Drag and drop file here",
        "upload_form.max_upload_size": "Max. upload size:"
      }
    }
  }
}
